### ISSUE TITLE
Construa uma API REST em C# com .NET CORE e Entity Framework Core

### ISSUE THREAD

**Issue by gfilenga** [balta-io/blog#1]
https://github.com/gfilenga/VaiVoa

Fala balta, tudo bem?

Vi seu anúncio no discord e queria ver o que você acha. Fiz esse repositório para um processo seletivo e, inclusive, ele já está em formato markdown.

Utilizei muitos conceitos que aprendi nos seus cursos e outras coisas de outros cursos e fontes também. O repositório do projeto e o respectivo "blog post" está no próprio arquivo "README" do repositório.

**Comment by andrebaltieri** [comment]
Sensacional @gfilenga acho que dá pra elaborarmos algo em cima disso sim. Eu conferi o repositório e está bem com cara de "processo seletivo".. O que acha de dar uma retocada para deixar mais com ar de artigo? Acho que ficaria sensacional <3

Outro ponto, não podemos referenciar outras empresas, beleza?

**Comment by gfilenga** [comment]
Perfeito, vou tirar essa cara de "processo seletivo" e mudar pra outro repositório e mando aqui mesmo o link do repositório novo.

Ai mudamos o que mais você achar que for necessário. Em breve mando o novo link.
