### ISSUE TITLE
Proposta de artigo:  Implementando o Health Checks em uma API dotnet5 para monitorar a saúde da aplicação

### ISSUE THREAD

**Issue by diegostan** [balta-io/blog#10]
#### Qual título do artigo?
=>  Implementando o Health Checks em uma API dotnet5 para monitorar a saúde da aplicação

#### Sobre o que você pretende falar neste artigo?
=> Nesse artigo gostaria de trazer a abordagem de monitoramento e disponibilidade de uma aplicação. Utilizando-se do recurso Health Checks presente no dotnet5, iremos instalar, configurar e aplicar o recurso em uma API onde iremos ver via dashboard e JSON o status da aplicação e da base de dados(SQL Server).

#### Qual previsão para submissão deste artigo?
=> 15/08/2021

**Comment by BrewertonSantos** [comment]
Opa @diegostan, Ótimo assunto! Simbora começar? Qualquer dúvida só sinalizar. Beleza?

**Comment by diegostan** [comment]
Show!! Já irei preparar tudo. Obrigado ❤❤

**Comment by andrebaltieri** [comment]
Fala @diegostan, bora tocar este artigo 💜

**Comment by diegostan** [comment]
Boa tarde pessoal, tive alguns problemas e não consegui finalizar na data prometida. Peço desculpas. Já finalizei e estarei abrindo um pull request. Abraços

**Comment by andrebaltieri** [comment]
@diegostan você submeteu como um submodule... por favor manda os arquivos diretamente neste repositório!

**Comment by diegostan** [comment]
@andrebaltieri posso dar um push diretamente?

**Comment by andrebaltieri** [comment]
@diegostan  Pode sim!

**Comment by diegostan** [comment]
@andrebaltieri estou recebendo um 403 na hora do push...

**Comment by andrebaltieri** [comment]
Você precisa fazer um PR pra branch main... Da outra vez você fez um PR mas enviando seu artigo como um submódulo... Precisamos dos arquivos direto no repositório... lemos eles daqui!

**Comment by diegostan** [comment]
@andrebaltieri agora entendi hahaha vlw

**Comment by diegostan** [comment]
@andrebaltieri  e @BrewertonSantos abri um PR ai, qualquer coisa me sinalizem por favor. Abraços

**Comment by andrebaltieri** [comment]
![image](https://user-images.githubusercontent.com/965305/133257527-735845f8-e086-4100-ad75-fd1525fafc13.png)

Artigo publicado! Parabéns @diegostan 
https://balta.io/blog/aspnet-health-check

**Comment by diegostan** [comment]
Obrigado @andrebaltieri e @BrewertonSantos  💙❤💜
