### ISSUE TITLE
Proposta de artigo:  Apresentar a biblioteca Refit e como a mesma pode simplificar o consumo de API's

### ISSUE THREAD

**Issue by diegostan** [balta-io/blog#15]
#### Qual título do artigo?
=> Simplificando o consumo de APIs com AspNet Refit

#### Sobre o que você pretende falar neste artigo?
=> A ideia é apresentar os recursos da biblioteca Refit e consumir uma API através de uma app ASP.NET, exemplificando como esse processo pode se tornar mais simples e limpo utilizando o Refit.

#### Qual previsão para submissão deste artigo?
=> 17/01/2022

**Comment by diegostan** [comment]
@andrebaltieri  Já comecei a escrita .

**Comment by andrebaltieri** [comment]
Sensacional!

**Comment by diegostan** [comment]
@andrebaltieri  Balta já subi o artigo, se quiser dar uma olhada, já está revisado e pronto para publicar. Abraços

**Comment by andrebaltieri** [comment]
Sensacional @diegostan!
@BrewertonSantos pode revisar por favor!

**Comment by BrewertonSantos** [comment]
@balta-io/devteam Revisão em andamento. Alinhando ajustes e detalhes para a publicação com o @diegostan.

**Comment by BrewertonSantos** [comment]
@andrebaltieri artigo pronto para ser publicado.

**Comment by BrewertonSantos** [comment]
Artigo publicado!
