### ISSUE TITLE
Proposta de artigo:  Blazor WASM PWA na Microsoft Store

### ISSUE THREAD

**Issue by andrebaltieri** [balta-io/blog#18]
#### Qual título do artigo?
=> Blazor WASM PWA na Windows Store

#### Sobre o que você pretende falar neste artigo?
=> Neste artigo vamos aprender a publicar uma PWA criada com Blazor WASM na Microsoft Store

#### Qual previsão para submissão deste artigo?
=> dd/MM/yyyy

**Comment by BrewertonSantos** [comment]
Feito! A previsão para submissão será Quinta, 30/09/2021.
