### ISSUE TITLE
Como fazer um login/logout com Angular, proteger as rotas e enviar o token de usuário nas requisições

### ISSUE THREAD

**Issue by GustavoRodrigues94** [balta-io/blog#2]
Fazer login/logout, muitas vezes, parece ser algo muito simples, porém, ao nos depararmos com a necessidade do mesmo, vemos que não é tão simples assim, ainda mais para quem não tem tanta intimidade com storage, route guards e token interceptors. No artigo, gostaria de explicar de forma simples e prática, como realizar um login/logout completo e funcional utilizando Angular.

**Comment by andrebaltieri** [comment]
Perfeito @GustavoRodrigues94, manda bala <3

**Comment by BrewertonSantos** [comment]
@GustavoRodrigues94 Tudo bom cara? É um assunto bem legal, tem previsão para a publicação?

**Comment by GustavoRodrigues94** [comment]
@BrewertonSantos, esse meu artigo já foi mergeado em Pull Requests, aqui no repositório. Tenho que fazer mais algo?

**Comment by BrewertonSantos** [comment]
Confirmadas as informações para prosseguir. Valeu pelo contato @GustavoRodrigues94 \o/

**Comment by andrebaltieri** [comment]
@BrewertonSantos pode subir novamente o arquivo seguindo o padrão (Criar pasta para o artigo e subir ele dentro dela)?
Se precisar de ajuda me fala!

@GustavoRodrigues94 desculpa demora, estavamos trabalhando em algumas melhorias e já vamos dar continuidade aos artigos!

**Comment by andrebaltieri** [comment]
Desculpa demora pessoal, já coloquei o artigo no padrão, esta semana vai para o ar!

**Comment by BrewertonSantos** [comment]
Artigo finalizado! Os arquivos estão revisados. Publicação hoje (23/09/2021).

**Comment by andrebaltieri** [comment]
@BrewertonSantos faltaram as imagens que aparecem no site
- login-logout-protecao-de-rotas-envio-de-tokens-com-angular_share.jpg
- login-logout-protecao-de-rotas-envio-de-tokens-com-angular_banner.jpg
- login-logout-protecao-de-rotas-envio-de-tokens-com-angular_icon.jpg

**Comment by BrewertonSantos** [comment]
@andrebaltieri estão nos arquivos: [ícone](https://github.com/balta-io/blog/blob/main/login-logout-protecao-de-rotas-envio-de-tokens-com-angular/images/login-logout-protecao-de-rotas-envio-de-tokens-com-angular_icon.jpg), [banner](https://github.com/balta-io/blog/blob/main/login-logout-protecao-de-rotas-envio-de-tokens-com-angular/images/login-logout-protecao-de-rotas-envio-de-tokens-com-angular_banner.jpg), [compartilhar](https://github.com/balta-io/blog/blob/main/login-logout-protecao-de-rotas-envio-de-tokens-com-angular/images/login-logout-protecao-de-rotas-envio-de-tokens-com-angular_share.jpg).

**Comment by andrebaltieri** [comment]
@GustavoRodrigues94 @BrewertonSantos artigo publicado!
https://balta.io/blog/login-logout-protecao-de-rotas-envio-de-tokens-com-angular
