### ISSUE TITLE
.Net core - injeção de dependência "Ciclo de vida " - singleton, scoped, transient

### ISSUE THREAD

**Issue by pauloteodoro** [balta-io/blog#24]
#### Qual título do artigo?
.Net core - injeção de dependência "Ciclo de vida " - singleton, scoped, transient.

#### Sobre o que você pretende falar neste artigo?
Sobre o ciclo de vida e como eles funcionam 

#### Qual previsão para submissão deste artigo?
=> 15/10/2021

**Comment by BrewertonSantos** [comment]
Olá @pauloteodoro muito bom o assunto, pode começar. Se precisar de auxilio durante o processo pode me procurar.

**Comment by pauloteodoro** [comment]
Ola, @BrewertonSantos, estarei escrevendo já fiz umas pesquisas, mas qualquer duvida dou um toque

**Comment by BrewertonSantos** [comment]
Olá @pauloteodoro, o artigo segue em desenvolvimento?

**Comment by pauloteodoro** [comment]
Ola sim , estou quase acabando

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by BrewertonSantos** [comment]
@pauloteodoro como está o progresso do artigo?

**Comment by BrewertonSantos** [comment]
@pauloteodoro Tudo bom Como está o progresso do artigo?

**Comment by BrewertonSantos** [comment]
@pauloteodoro Beleza? Novidades?

**Comment by andrebaltieri** [comment]
Não houve continuidade no artigo!
