### ISSUE TITLE
Proposta de artigo:  Utilizando o Discord como repositório de log em .NET

### ISSUE THREAD

**Issue by jlnpinheiro** [balta-io/blog#25]
#### Qual título do artigo?
=> Utilizando o Discord como repositório de log em .NET

#### Sobre o que você pretende falar neste artigo?
=> Gostaria de mostrar como instalar e utilizar um componente desenvolvido por mim, que permite logar infornações em um canal do Discord (utilizando o Discord como um provider para utilização de ILogger). O repositório do componente desenvolvido está disponível em https://github.com/jlnpinheiro/logger-discord-provider

#### Qual previsão para submissão deste artigo?
=> 20/01/2022 (segunda quinzena de janeiro/2022).

**Comment by BrewertonSantos** [comment]
Opa! Proposta legal, pode começar. Se precisar de auxílio pode me procurar no discord ou marcar aqui no github mesmo.

**Comment by BrewertonSantos** [comment]
@jlnpinheiro como está o progresso?

**Comment by jlnpinheiro** [comment]
Grande Brew! Volto de férias amanhã! Acho q vou atrasar, pq pintaram outras demandas! Podemos jogar o artigo pra fevereiro?

**Comment by BrewertonSantos** [comment]
@jlnpinheiro Belezura, sem problemas. Vamos nessa! 💜

**Comment by BrewertonSantos** [comment]
@jlnpinheiro tudo bom? Como está o andamento do artigo?

**Comment by andrebaltieri** [comment]
Artigo publicado!
