### ISSUE TITLE
Proposta de artigo:  Linguagens de Programação Compiladas x Interpretadas: quais as diferenças?

### ISSUE THREAD

**Issue by jeancarlospaula** [balta-io/blog#26]
#### Qual título do artigo?
=> Linguagens de Programação Compiladas x Interpretadas: quais as diferenças?

#### Sobre o que você pretende falar neste artigo?
=> As diferentes maneiras de execução/tradução de uma linguagem de programação:  Compiladas, Interpretadas e Pré-compiladas (JIT)
https://www.linkedin.com/pulse/linguagens-de-programa%C3%A7%C3%A3o-compiladas-x-interpretadas-quais-de-paula/

#### Qual previsão para submissão deste artigo?
=> 15/01/2022

**Comment by BrewertonSantos** [comment]
@jeancarlospaula Muito bom! Assim como o artigo anterior, peço que submeta o pull request com o artigo em markdown e as imagens, de acordo com as instruções do README. Qualquer dúvida só me marcar.

**Comment by jeancarlospaula** [comment]
PR enviado!

**Comment by BrewertonSantos** [comment]
@jeancarlospaula Bom dia! O pr não chegou por aqui!

**Comment by andrebaltieri** [comment]
Não houve continuidade no artigo!
