### ISSUE TITLE
Proposta de artigo:  Linguagens de Manipulação de Dados: Conheça o SQL!

### ISSUE THREAD

**Issue by jeancarlospaula** [balta-io/blog#27]
#### Qual título do artigo?
=> Linguagens de Manipulação de Dados: Conheça o SQL!

#### Sobre o que você pretende falar neste artigo?
=> Introdução ao SQL
https://www.linkedin.com/pulse/linguagens-de-manipula%25C3%25A7%25C3%25A3o-dados-conhe%25C3%25A7a-o-sql-jean-carlos-de-paula/?trackingId=OhhBuK1WdAM5HvMFOXBzFA%3D%3D

#### Qual previsão para submissão deste artigo?
=> 15/01/2022

**Comment by BrewertonSantos** [comment]
Opa! Vamos agendar a publicação 💜

**Comment by jeancarlospaula** [comment]
Opa claro! ✌🏻

**Comment by BrewertonSantos** [comment]
@jeancarlospaula Pode submeter um pull request com o artigo e as imagens? Já formulei a publicação para a quarta-feira. Tudo bem?

**Comment by BrewertonSantos** [comment]
@jeancarlospaula você criou um fork do projeto. Se estiver com dificuldades no uso do git pode me procurar no discord ou aqui mesmo.

**Comment by jeancarlospaula** [comment]
PR enviado!

**Comment by jeancarlospaula** [comment]
> @jeancarlospaula você criou um fork do projeto. Se estiver com dificuldades no uso do git pode me procurar no discord ou aqui mesmo.

@BrewertonSantos realmente da proxima faço direto de um repositório meu hehehe

**Comment by andrebaltieri** [comment]
Pessoal, a PR estava para a `main`. Criei uma branch para o artigo, está aqui:
https://github.com/balta-io/blog/blob/introducao-linguagem-manipulacao-dados-sql/introducao-linguagem-manipulacao-dados-sql/index.md

Aguardo a revisão de vocês e padronização para mergear esta branch com a principal e publicar o artigo!

**Comment by BrewertonSantos** [comment]
@jeancarlospaula o artigo está atualmente com 490 palavras. Como descrito nas instruções, esperamos um mínimo de 1500 palavras. Se puder adicionar mais conteúdo ao artigo será bem legal.

**Comment by BrewertonSantos** [comment]
@jeancarlospaula a imagem utilizada nos conjuntos é derivada da web. É necessário citar a referência onde encontrar a imagem e opicionalmente o nome do autor na descrição.

**Comment by jeancarlospaula** [comment]
> @jeancarlospaula o artigo está atualmente com 490 palavras. Como descrito nas instruções, esperamos um mínimo de 1500 palavras. Se puder adicionar mais conteúdo ao artigo será bem legal.

Opa beleza. Só que agora durante a semana está bem corrido. Consigo fazer isso fiz de semana

**Comment by jeancarlospaula** [comment]
@BrewertonSantos realizei as alterações quanto as referencias!

**Comment by BrewertonSantos** [comment]
@jeancarlospaula Por gentileza pode verificar o tamanho do artigo? Temos algumas instruções definidas no [README do projeto](https://github.com/balta-io/blog#readme)

**Comment by jeancarlospaula** [comment]
@BrewertonSantos claro vejo sim. Esse fim de semana aliás, essa semana em si está complicado pois estou viajando a trabalho e não consegui parar ainda para escrever, só estou estudando. Acredito que até fim de semana conseguirei adicionar mais topicos ao artigo!

**Comment by BrewertonSantos** [comment]
@jeancarlospaula Tudo bem? Caso tenha dúvidas com o artigo só marcar ou chamar no  discord mesmo. Beleza?

**Comment by BrewertonSantos** [comment]
@jeancarlospaula Tudo bom? Houve progresso?
