### ISSUE TITLE
Proposta de artigo:  Trabalhando com múltiplos Layouts no Blazor

### ISSUE THREAD

**Issue by MensoDev** [balta-io/blog#36]
#### Qual título do artigo?
=> Trabalhando com múltiplos Layouts no Blazor

#### Sobre o que você pretende falar neste artigo?
=> Como trabalhar com múltiplos Layouts no Blazor, tornando a aplicação mais dinâmico a cenários se adaptando as necessidades. 

#### Qual previsão para submissão deste artigo?
=> 10/02/2022

**Comment by BrewertonSantos** [comment]
Opa! Teremos um dos primeiros artigos em BLAZOR!! Vamos lá @kerygma-dev. Se tiver qualquer dúvida pode me procurar aqui ou no discord.

**Comment by BrewertonSantos** [comment]
Olá @kerygma-dev Tudo bom? Está dando certo o artigo? Caso precise de algo nos marca aqui que podemos auxiliar.

**Comment by kerygma-dev** [comment]
Oi @BrewertonSantos tudo bem sim, e com você? estou so um pouco atrapalhado porque estou fazendo um projeto de test para uma vaga na dotkon, ai talvez eu me atraze um ou dois dias no previsão de entrada tudo bem?

**Comment by kerygma-dev** [comment]
@BrewertonSantos tudo bem? cara minha vida deu umas voltas e estou em um nova empresa! em fim, quanto ao artigo eu peço mais 10 dias, que agora vou poder voltar a construir novamente o artigo!

**Comment by BrewertonSantos** [comment]
Opa, Parabéns então pelo novo emprego. Beleza, ficamos no aguardo.

**Comment by andrebaltieri** [comment]
Não houve continuidade no artigo!
