### ISSUE TITLE
Proposta de artigo: Executando processamentos em segundo plano no .NET com o Hangfire

### ISSUE THREAD

**Issue by lucasdemoraesc** [balta-io/blog#37]
#### Qual título do artigo?
=> Executando processamentos em segundo plano no .NET com o Hangfire

#### Sobre o que você pretende falar neste artigo?
=> Como utilizar a biblioteca Hangfire para executar jobs pré agendadas, ou não _(fire and forget)_, fora do pipeline de execução da aplicação e como utilizar o dashboard implementado pela biblioteca para gerenciar suas jobs.

#### Qual previsão para submissão deste artigo?
=> 10/02/2022

**Comment by lucasdemoraesc** [comment]
Faaala @BrewertonSantos e @andrebaltieri!!
Beleza ?

Gostaria de confirmar a proposta do meu tema rsrs, posso seguir com a elaboração ? O que acham ?

**Comment by BrewertonSantos** [comment]
Opa @lucasdemoraesc! Pode iniciar, se tiver qualquer dúvida pode me marcar.

**Comment by BrewertonSantos** [comment]
@lucasdemoraesc Tudo bem por ai? Apenas confirmando sobre o artigo. Se precisar de algo nos chama, beleza?
