### ISSUE TITLE
Proposta de artigo:  É viável programar em C# no Linux em 2022?

### ISSUE THREAD

**Issue by JGMelon22** [balta-io/blog#40]
#### Qual título do artigo?
=> É viável programar em C# no Linux em 2022?

#### Sobre o que você pretende falar neste artigo?
=> Se é possível desenvolver com C# em outra plataforma (nesse caso, Linux) sem muita preocupação e com qualidade de vida para o desenvolvedor.

#### Qual previsão para submissão deste artigo?
=> 09/02/2022

**Comment by BrewertonSantos** [comment]
Revisado e agendado. Parabéns!
