### ISSUE TITLE
Proposta de artigo:  Manipulação de elementos DOM Angular

### ISSUE THREAD

**Issue by marophius** [balta-io/blog#46]
#### Qual título do artigo?
=> Manipulação de elementos DOM Angular

#### Sobre o que você pretende falar neste artigo?
=> Boas práticas recomendadas para realizar acesso e manipulação da DOM Angular

#### Qual previsão para submissão deste artigo?
=> 29/02/2022

**Comment by BrewertonSantos** [comment]
@marophius Olá! Uma boa proposta é sempre bem-vinda! Parabéns. Caso tenha dúvidas no processo pode me procurar ou ao balta. Aqui mesmo no github ou no nosso discord: https://balta.io/discord

**Comment by andrebaltieri** [comment]
Não houve continuidade no artigo!
