### ISSUE TITLE
Criando um DelegatingHandler para Autorizações

### ISSUE THREAD

**Issue by myersBR** [balta-io/blog#47]
#### Qual título do artigo?
=> Criando um DelegatingHandler para autorizações

#### Sobre o que você pretende falar neste artigo?
=> Criação de um DelegatingHandler para adicionar autorizações em chamadas Http

#### Qual previsão para submissão deste artigo?
=> 14/03/2022

**Comment by BrewertonSantos** [comment]
@myersBR  Olá e perdão pelo tempo de resposta para sua solicitação. Proposta muito interessante, pode começar a desenvolver o artigo. Caso tenha dúvidas ou qualquer dificuldade no processo pode me marcar aqui ou me procurar no Discord da comunidade.

**Comment by BrewertonSantos** [comment]
Olá @myersBR. Tudo certo? Como está o andamento?

**Comment by BrewertonSantos** [comment]
@myersBR Tudo bom? Como está o progresso? Caso tenha qualquer dúvida só me marcar. Beleza?

**Comment by andrebaltieri** [comment]
Não houve continuidade no artigo!
