### ISSUE TITLE
Proposta de artigo:  Testes de mutação com Stryker.NET

### ISSUE THREAD

**Issue by Eliandro-Freitas** [balta-io/blog#49]
#### Qual título do artigo?
=> Testes de mutação com Stryker.NET

#### Sobre o que você pretende falar neste artigo?
=> Testes unitários usando Stryker.NET que é uma biblioteca que oferece testes de mutação para .NET

#### Qual previsão para submissão deste artigo?
=> 31/03/2022

O artigo será exclusivo para a plataforma balta.io.

**Comment by BrewertonSantos** [comment]
Ótimo tema. Pode começar, caso tenha dúvidas ou precise de auxilio pode me marcar.

**Comment by Eliandro-Freitas** [comment]
Olá, como funciona o processo de PR? Vai ser revisado apenas no dia que coloquei como previsto para submissão?

**Comment by BrewertonSantos** [comment]
@Eliandro-Freitas já foi revisado o PR. Logo passarei ele para à publicação. Beleza?

**Comment by Eliandro-Freitas** [comment]
Opa, muito obrigado !

**Comment by BrewertonSantos** [comment]
artigo publicado.
