### ISSUE TITLE
Criando uma API do zero com .NET Core 3.1 e EF Core

### ISSUE THREAD

**Issue by jhonatafernandes** [balta-io/blog#5]
Blog post que ensina a como criar uma API simples do zero usando alguns fundamentos do SOLID, Clean Code e notificações com o Flunt.

**Comment by andrebaltieri** [comment]
OK! Manda bala :)

**Comment by BrewertonSantos** [comment]
Opa! Olá, olá! @jhonatafernandes como está o andamento deste artigo? Assunto interessante, quero ler quando sair. 😄

**Comment by jhonatafernandes** [comment]
Opa Balta, eu já tinha escrito o artigo desde a  abertura da ISSUE, mas
como tive problemas ao subir o PR acabei esquecendo de tentar novamente.
Eu estava tendo problemas de acesso negado ao tentar subir um PR, tem
alguma outra configuração que devo fazer?

Em qua., 4 de ago. de 2021 às 10:43, Andre Baltieri <
***@***.***> escreveu:

**Comment by andrebaltieri** [comment]
@BrewertonSantos consegue ajudar ele com o PR?

**Comment by BrewertonSantos** [comment]
Opa! @jhonatafernandes, está dando certo o desenvolvimento do artigo? Precisando de qualquer coisa pode entrar em contato

**Comment by andrebaltieri** [comment]
@jhonatafernandes muito obrigado pela submissão!
https://github.com/balta-io/blog/blob/main/criando-uma-api-do-zero/

Vou revisar e agendar para próxima semana 💜

**Comment by andrebaltieri** [comment]
@jhonatafernandes poderia fornecer uma descrição de até 160 caracteres sobre o que você fala no artigo e também algumas tags. Vou deixar uma sugestão abaixo

```
---
title: Criando uma API do zero com .NET Core 3.1 e EF Core
description: Neste artigo vamos aprender a criar uma API do ZERO com ASP.NET Core 3.1 e EF Core.
tags: aspnte, ef, efcore, dotnet
---
```

**Comment by jhonatafernandes** [comment]
Título: Criando uma API do zero com .NET Core 3.1 e EF Core
Descrição: Neste artigo vamos criar uma API do zero utilizando o ASP.NET
Core 3.1, EF Core e alguns conceitos essenciais na construção de APIs. Vem
conferir!
Tags: api, aspnet, efcore, dotnet, injeção de dependência, domínios ricos,
solid, clean code

Em dom., 15 de ago. de 2021 às 23:46, Andre Baltieri <
***@***.***> escreveu:

**Comment by andrebaltieri** [comment]
@BrewertonSantos consegue dar uma revisada e ver se tudo está OK no artigo?
Se sim, coloca na nossa agenda no Asana para agendarmos a publicação!

**Comment by andrebaltieri** [comment]
@BrewertonSantos deu certo revisar e colocar na nossa agenda?

**Comment by BrewertonSantos** [comment]
@jhonatafernandes @balta-io/devteam. Okay! Preparando a públicação.

**Comment by andrebaltieri** [comment]
@BrewertonSantos por favor move o card no board qdo estive tudo OK <3

**Comment by andrebaltieri** [comment]
@BrewertonSantos como está este artigo?

**Comment by BrewertonSantos** [comment]
@jhonatafernandes o artigo será publicado na próxima segunda-feira (27/09/2021) Tudo bem?

**Comment by jhonatafernandes** [comment]
Sem problemas. Obrigado, pessoal!

Em qui., 23 de set. de 2021 às 12:42, Brewerton ***@***.***>
escreveu:

**Comment by andrebaltieri** [comment]
@jhonatafernandes @BrewertonSantos 
Publicado: https://balta.io/blog/criando-api-zero-dotnet-core-3-1-ef-core
