### ISSUE TITLE
Proposta de artigo: O que é um Framework?

### ISSUE THREAD

**Issue by CristianoBNoronha** [balta-io/blog#52]
#### Qual título do artigo?
=> O que é um Framework?

#### Sobre o que você pretende falar neste artigo?
=>  O que são, e como funcionam os Frameworks; O que são frameworks frontend e backend, qual a diferença entre eles; Citar frameworks mais usados e suas características; Citar as fontes para Frameworks;  Quais questões relacionadas ao uso de frameworks na nossa aplicação; Como podemos melhorar o uso de Frameworks na nossa aplicação.

#### Qual previsão para submissão deste artigo?
=> 20/04/2022

**Comment by BrewertonSantos** [comment]
Ollá Cristiano, tudo bom?

Parabéns pelo tema! É muito bom ter artigos falando sobre frameworks para introduzir o pessoal. Se precisar de auxilio durante o desenvolvimento pode enviar aqui.

**Comment by CristianoBNoronha** [comment]
Eu criei um fork, e estou trabalhando nele. Eu vou mandando cada avanço para o repositório  balta.io/blog, ou no termino mando tudo de uma vez?

**Comment by CristianoBNoronha** [comment]
Olá, boa tarde!
Eu não estou conseguindo fazer o push.
Podem me ajudar? Segue a mensagem de erro.

remote: Permission to balta-io/blog.git denied to CristianoBNoronha.
fatal: unable to access 'https://github.com/balta-io/blog.git/': The requested URL returned error: 403

**Comment by BrewertonSantos** [comment]
@CristianoBNoronha vamos verificar e já retorno à você. Obrigado por avisar!

**Comment by BrewertonSantos** [comment]
Publicado!
