### ISSUE TITLE
Proposta de artigo:  Git: Por dentro do encanamento

### ISSUE THREAD

**Issue by ozmartins** [balta-io/blog#58]
#### Qual título do artigo?
=> Git: Por dentro do encanamento

#### Sobre o que você pretende falar neste artigo?
=> Falar sobre os mecanismos internos que o Git usa para gerenciar as mudanças nos arquivos de um diretório. Minha principal referência será o e-book oficial do Git que está disponível no site git-scm.com. O meu objetivo com o artigo é que os usuários do sistema saibam como ele funciona internamente e, assim, consigam tirar melhor proveito da ferramenta.

#### Qual previsão para submissão deste artigo?
=> 02/05/2022

**Comment by BrewertonSantos** [comment]
Olá @ozmartins!

Proposta interessante, apenas deixando uma notificação para que verifique os artigos de git já existentes para ver se não vai repetir algum assunto. Mas pelo que apresentou acredito que é algo novo. Prossiga e espero para ler ele também kk

**Comment by BrewertonSantos** [comment]
Fechando o issue! Artigo publicado: https://balta.io/blog/git-por-dentro-do-encanamento
