### ISSUE TITLE
Proposta de artigo: Criando e reutilizando workflows no GitHub Actions.

### ISSUE THREAD

**Issue by hstrada** [balta-io/blog#61]
#### Qual título do artigo?
=> Criando workflows reutilizáveis no GitHub Actions

#### Sobre o que você pretende falar neste artigo?
=> Pretendo apresentar brevemente sobre o GitHub Actions.
E na sequência, apresentar duas abordagens para criar workflows reutilizáveis conforme os exemplos apresentados nesses repositórios.
https://github.com/Wechoo/workflow-templates/tree/master/.github/workflows
https://github.com/Wechoo/.github/tree/master/workflow-templates

#### Qual previsão para submissão deste artigo?
=> 12/06/2022

**Comment by hstrada** [comment]
@BrewertonSantos Como vou apresentar duas maneiras diferentes de "reutilizar" fluxos de trabalho no GitHub Actions, estava pensando em outro nome como:
Criando e reutilizando fluxos de trabalho no GitHub Actions.
Você acha que faz sentido? Obrigada.

**Comment by BrewertonSantos** [comment]
@hstrada Dependendo do tamanho que pode estar tomando o artigo ele pode ser dividido em duas partes. Mas se considerar que ele não está extenso e os dois temas podem ser tratados em um só, o título pode ser modificado sim, sem problemas. Ok?

**Comment by hstrada** [comment]
@BrewertonSantos combinado! aceito sugestões ao término! quase lá!

**Comment by BrewertonSantos** [comment]
@hstrada Tudo bem? Como está o progresso? Caso considere que podemos auxiliar, pode marcar aqui ou no discord. 👊

**Comment by hstrada** [comment]
> @hstrada Tudo bem? Como está o progresso? Caso considere que podemos auxiliar, pode marcar aqui ou no discord. 👊

ei, @BrewertonSantos bom dia! estou fazendo a última revisão antes de encaminhar para vocês. Obrigada pelo suporte na jornada!
