### ISSUE TITLE
Proposta de artigo:  Trabalhando mais de uma configuração do git em um único computador

### ISSUE THREAD

**Issue by liandro-wesley** [balta-io/blog#67]
#### Qual título do artigo?
=> Trabalhando mais de uma configuração do git em um único computador

#### Sobre o que você pretende falar neste artigo?
=>  Pretendo apresentar inicialmente o que é o arquivo .gitconfig. Em seguida, apresentar uma maneira de organizar o .gitconfig para que você possa assinar, por exemplo, um e-mail diferente em um commit de determinado projeto sem precisar fazer isso dentro de cada projeto que for trabalhar

#### Qual previsão para submissão deste artigo?
=> 09/07/2022

**Comment by andrebaltieri** [comment]
@liandro-wesley manda bala <3

**Comment by liandro-wesley** [comment]
@andrebaltieri valeu meu chapa : )

**Comment by liandro-wesley** [comment]
@andrebaltieri @BrewertonSantos Creio que finalizei a parte mais básica da config, relativo a assinatura de e-mail e nome... Teria problema abrir uma outra issue para publicar a continuação deste artigo? Pretendo mostrar no próximo como ter mais de uma chave ssh registrada na máquina, e ainda assim aplicar, por exemplo, uma para cada empresa ou tipo de projeto....

Utlizarndo serviços como o GitHub, BitBucket, GitLab e Azure Devops...

**Comment by BrewertonSantos** [comment]
@liandro-wesley Legal demais cara! Vamos lá. Você pode fazer o PR deste? Ai já verificamos e alinhamos bem. Enquanto isto você pode ir escrevendo a próxima parte!

**Comment by liandro-wesley** [comment]
Sim, claro! Aqui está o link da PR 
https://github.com/balta-io/blog/pull/68

**Comment by liandro-wesley** [comment]
@BrewertonSantos tu tens alguma consideração quanto ao artigo? Não consegui finalizar a segunda parte como desejava, acabei tendo uma série de imprevistos, mas, na próxima semana vou finalizar!

**Comment by andrebaltieri** [comment]
Bom dia, @liandro-wesley, como vai? Aprovado seu artigo.. utilizarei as informações do seu perfil do GitHub no dia de divulgar o artigo, OK?

**Comment by liandro-wesley** [comment]
Ok, sem problemas Balta, que showww cara, já posso ficar ansioso, é isso? ahahahahah

**Comment by andrebaltieri** [comment]
@liandro-wesley já pode sim, em breve sai e te marco!! Muito obrigado!
