### ISSUE TITLE
Utilizando Tuples no C#

### ISSUE THREAD

**Issue by JoaoNascSilva** [balta-io/blog#7]
Bom Dia Balta, gostaria de escrever sobre a utilização de Tuples no C# !

**Comment by BrewertonSantos** [comment]
Opa!!! Tudo bom João? Muito bom. Para confirmar, poderia deixar abaixo o título do artigo, tópicos que pretende abordar e a data prevista? Ai já podemos organizar enquanto você produz o artigo, beleza?

**Comment by andrebaltieri** [comment]
@JoaoNascSilva como está por ai? Precisa de ajuda com algo?

**Comment by JoaoNascSilva** [comment]
Boa Tarde @andrebaltieri e @BrewertonSantos , desculpe a demora. Mas nesses dois últimos meses meu pai estava com problema de saúde, e eu estava ajudando ele (outra cidade), melhor agora graças a Deus. e no início deste mês estou trocando de emprego e está meio corrido.
Mas vou por pra rodar este artigo sim !

**Comment by andrebaltieri** [comment]
Sem problemas @JoaoNascSilva, melhoras ai 💜

**Comment by andrebaltieri** [comment]
Faaaaala @JoaoNascSilva, bora retomar este artigo <3

**Comment by andrebaltieri** [comment]
E ai @JoaoNascSilva bora tocar esse artigo hahahaha
É um tema interessante, seria muito bacana... Revisamos e te ajudamos se precisar!

**Comment by JoaoNascSilva** [comment]
Opa, vamos sim @andrebaltieri eu estava com pouco tempo, mas a partir dessa semana já começo !

**Comment by BrewertonSantos** [comment]
@JoaoNascSilva Tudo bom? Caso tenha alguma dúvida pode me marcar aqui ou lá no discord: https://balta.io/discord

**Comment by BrewertonSantos** [comment]
@JoaoNascSilva Tudo certo? Como está o progresso?

**Comment by BrewertonSantos** [comment]
Ping! @JoaoNascSilva tudo certo? Houve progresso?

**Comment by BrewertonSantos** [comment]
@JoaoNascSilva tudo certo por ai?

**Comment by BrewertonSantos** [comment]
Como o artigo está ocioso por muito tempo e já foi publicado um semelhante. Irei fechar este issue. @JoaoNascSilva Caso queira escrever outro artigo no futuro, sinta-se a vontade. E se tiver dúvidas ou dificuldade estamos sempre por aqui e no discord também.
