### ISSUE TITLE
Migrations com .NET 5 e PostgreSQL

### ISSUE THREAD

**Issue by mar1zzo** [balta-io/blog#8]
Se você não pode, ou mesmo não quer, utilizar MySQL em sua API-REST no .NET 5, leia esse artigo até o final e certamente conseguirá usar com PostgreSQL.
...
Infelizmente, meu computador atual não suporta a instalação do MySQL. Sendo iniciante, precisei pesquisar muito sobre criação de Migrations no .NET 5 com PostgreSQL. Não encontrei nenhum artigo com esta especificidade, mas coletei em diferentes artigos da documentação da Microsoft e tive sucesso. Com o objetivo de facilitar a busca de outros colegas no futuro, resolvi escrever meu primeiro artigo com os passos que executei e fontes de consulta. 
Link do artigo para análise: https://medium.com/@morallesrizzo/migrations-no-postgresql-com-net-5-b39d2ca18140

Ps. Mesmo que não seja interessante para o canal Balta.io, agradeço se puderem compartilhar feedbacks.

**Comment by BrewertonSantos** [comment]
Opa, tudo bom? lá na página principal do repositório você vai encontrar instruções de como submeter o artigo. Qualquer dúvida pode marcar aqui ou no discord, beleza?

**Comment by mar1zzo** [comment]
Perfeito, Brewerton! Vou adaptar o artigo para a sintaxe correta do Markdown e faço o Pull Request. Mais uma vez, obrigada!

**Comment by andrebaltieri** [comment]
@mar1zzo como estão as coisas por ai? Precisa de ajuda com algo?

**Comment by mar1zzo** [comment]
Oi Balta, tudo bem? Desculpe, eu que não consegui me organizar para adaptar o artigo para o Markdown. Mas acredito que consigo no próximo final de semana.

**Comment by andrebaltieri** [comment]
@mar1zzo que isso, não precisa se desculpar! Veja quando pode e nos retorna aqui 💜

**Comment by andrebaltieri** [comment]
@mar1zzo obrigado pela submissão! Validei seu PR, vou preparar o artigo para ser publicado <3

**Comment by andrebaltieri** [comment]
@mar1zzo publicado:
https://balta.io/blog/migrations-efcore-dotnet-postgresql

Vou divulgar nas redes sociais e sai no nosso newsletter de sexta!
Parabéns <3
