### ISSUE TITLE
Proposta de artigo:  Uma abordagem sobre autenticação: Session | Token

### ISSUE THREAD

**Issue by Icegreeen** [balta-io/blog#91]
#### Qual título do artigo?
=> Uma abordagem sobre autenticação: Session | Token

#### Sobre o que você pretende falar neste artigo?
=> Assistindo os vídeos sobre autenticação no Balta, tive a ideia sobre escrever um artigo na qual aborda as duas práticas, assim, dando um contexto complementar relacionado ao tema. Dessa forma, o aluno ao assistir o vídeo, caso procure no blog uma contextualização mais completa ele terá um artigo sobre isso.

#### Qual previsão para submissão deste artigo?
=> 10/09/2023

**Comment by andrebaltieri** [comment]
@Icegreeen manda bala!
